name: Release / Publish Executables

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [arm, amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "dead-link-linter"
          extra_files: LICENSE README.md
